### ISSUE TITLE
mount snapshot contains non dom nodes

### ISSUE THREAD

**Issue by bsr203** [trayio/enzyme-to-json#9]
Hello,

While comparing the rendered output of `enzyme-to-json` (enzyme mount) with  `react-test-renderer`, I see the snapshot though enzyme-to-json contains all the HOC and other react components. This causes two issues

1. huge snapshot file (4313 lines vs 1468) and it is hard to see the changes in the diff.
2. change in source code which doesn't affect the dom (passing extra props, refactor to multiple component, ..) cause cause the test to fail. This is against the focussed test benefits.

Is there a way to only output real dom nodes if one uses `mount` ?

thanks.

**Comment by adriantoine** [comment]
Hi @bsr203,

I'm very open to any improvements on this library. My primary objective was to be as close as possible to the output of the `wrapper.debug()` method, which shows your wrapper in a nice HTML-like syntax. For example:
```html
<ClassWithPure className="class">
  <div className="class-with-pure class" onClick={[Function]}>
    <BasicPure className="nested-pure">
      <div className="basic-pure nested-pure" onClick={[Function]}>
        <div id="group-id" className="group">
          <span>
            <span>
              <strong>
                Hello!
              </strong>
            </span>
            <span className="empty" />
          </span>
          <span className="empty" />
        </div>
      </div>
    </BasicPure>
  </div>
</ClassWithPure>
```
is the output of the debug method on [the wrapper in my tests](https://github.com/trayio/enzyme-to-json/blob/master/test/mount.test.js#L26-L28), and this one shows the HOC and components props.
It could actually be helpful sometimes, for example:
```html
<Page className="class">
  <Menu onIconClick={[Function]}>
    <div className="icon" onClick={[Function]}>😎</div>
    <div className="menu-item">Item</div>
  </Menu>
</Page>
```
For some reason (a bug in my code), the `Page` component doesn't set the `onIconClick` prop to `Menu`:
```html
<Page className="class">
  <Menu>
    <div className="icon" onClick={[Function]}>😎</div>
    <div className="menu-item">Item</div>
  </Menu>
</Page>
```
it doesn't have any impact on the DOM because the `onClick` will still be set by `Menu`, but it is still a bug and I would still like it to be raised by my unit tests and at the moment that's how it works and I'd like it to keep working like that.

If you want your tests to be only focused on the DOM, you can use the [`render` Enzyme wrapper](https://github.com/airbnb/enzyme/blob/master/docs/api/render.md) which works with `renderToJson` or have tests more focused on the DOM elements using `.find()`, for example here I could have done:
```js
expect(mountToJson(wrapper.find('.icon'))).toMatchSnapshot();
```
and that issue about `onIconClick` not being set wouldn't be raised by my tests.

However as I said, I'm open to improvements to I can add an option to the `xxxToJson` function to only show DOM nodes, it wouldn't be too hard to implement, let me know what you think, if the `render` wrapper doesn't solve your issue?

**Comment by bsr203** [comment]
thank you for the detailed response. I agree with you, having the react component and props in the snapshot has great value. File size should not be a big concern as jest is improving how it displays diff as it only going to show only the difference in watch mode. The user interface arounf jest watch is super sleek so one can update the snapshot with a keystroke so keeping up with the change in component name, props, etc may not be tedious.

Please close this, unless you want to track the `onClick` you mentioned above.

thank again for your time.

**Comment by adriantoine** [comment]
No problem thanks for your suggestions

**Comment by bsr203** [comment]
@adriantoine is there an easy way to make it configurable, so that I can suppress the react component and just output dom elements in the snapshot. I had difficulty with components which takes large structure as props. For example, if a component takes a schema object as below, and pass through few more child component, the whole object is repeated in the snapshot. It would be great if we have a mode, which filters react components and props.

thanks.

```
<div
       className="queryBuilder">
            <Group
                  schema={
                Object {
                  "properties": Object {
                    "age": Object {
                      "type": "number",
                    },
                    "id": Object {
                      "type": "string",
                    },
                    "name": Object {
                      "type": "string",
                    },
                    "status": Object {
                      "type": "string",
                    },
                  },
                  "type": "object",
                }
              }
              onChange={[Function]}

```

**Comment by pedrottimark** [comment]
Happy New Year, Adrien.

There are examples of matching an object with DOM nodes only in a conversation https://github.com/facebook/jest/issues/2202#issuecomment-268347718 about `toMatchObject` assertion.

In the example of a diff snapshot for **Update** operations on a table cell, the result of enzyme traversal is a wrapper which contains only DOM nodes, as you suggested in a comment above.

In other examples, wrapper contains `TableRow` components which need to be omitted because:

* in snapshots of table for **Read** operations, component props are redundant with contents of `tr` and `td` elements
* in subset matches on table body for **Create** and **Delete** operations, we want to copy and edit an “external” snapshot of the table to become an “internal” snapshot of the table body

What do you think?

A suggestion for exported function name is `mountedDomToObject` because

* `mounted` as adjective seems a bit clearer to me than `mount` as imperative verb
* `Object` is parallel to `toMatchObject` assertion
* the symbol value of `$$typeof` property makes the returned object technically not valid JSON

If you are interested to add this function to `enzyme-to-json` I might have some additional details about small differences between output from enzyme mounted wrapper and from `react-test-renderer` which affected the subset matching.

Also, after https://github.com/facebook/jest/issues/2351 is closed, what do you think about making `$$typeof` a non-enumerable property in the object returned from this new function to make it as compatible as possible with `react-test-renderer`? For your info, the `enzyme-to-json` tests passed after I modified  `mount.js`, `render.js`, and `shallow.js` to follow the pattern in https://github.com/facebook/react/blob/master/src/renderers/testing/ReactTestRenderer.js#L112-L120

**Comment by pedrottimark** [comment]
@adriantoine Commenting to ask if you are willing to reopen and receive a pull request?

Goal is the received value for `toMatchObject` even more than `toMatchSnapshot` assertion.

There is a sample project to explain why and how. Your critique is welcome by opening issues.

You might start to read at this section:
https://github.com/pedrottimark/whimper#interlude-about-snapshot-testing

To get full benefit requires a function proposed for `react-test-renderer` but one step at a time :)
